[build]
builder = "nixpacks"
buildCommand = "cd apps/api && npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "cd apps/api && npm run start:prod"
healthcheckPath = "/api"
healthcheckTimeout = 300
